// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uemxjhzuhmkrkpjskmyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbXhqaHp1aG1rcmtwanNrbXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTE1MzQsImV4cCI6MjA2MTM2NzUzNH0.W3yt6xS0YlwZCUnUXr1jik0EP2yVx8pNZyYU5s9Gw8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);